### PR TITLE
Epic/2 yes no voting

### PR DESCRIPTION
**Pull request by sebasruii**
Complete implementation of yes/no voting.
This pull request resolves the following incidents:
#49 #58 #86 #96 #99 #135 #140 and #153

### CODE REVIEW

**Comment by alvarobernal2412** [comment]
This PR is going to be reopened to restart the CI.

**Comment by alvarobernal2412** [comment]
A new feature has been added to the CI, enabling restart via the **_ready_** label. Beforehand, you'll need to copy the commit from 'develop' containing the latest updates.

**Review by Thealean28 — APPROVED** [review]
All changes are OK

**Comment by josgarber6** [comment]
This PR solve the issue #207

**Pull request merged**
