### PR TITLE
fix: Corrected and added visualizer tests #236

### PR DESCRIPTION
**Pull request by alejandromd**
Problems related to tests in visualizer have been corrected after the implementation of more voting types. More tests have also been added.
Renamed the file test.py to tests_selenium.py
This PR will resolve the incident #236

### CODE REVIEW

**Review by josgarber6 — CHANGES_REQUESTED** [review]
The tests run perfectly, but there is a wrong thing. The name of tests_selenium.py should be test_selenium.py

**Comment by alejandromd** [comment]
I have renamed the file to _test_selenium.py_

**Review by josgarber6 — APPROVED** [review]
Everything is fine

**Review by Thealean28 — APPROVED** [review]
All changes are fine.

**Pull request merged**
