### PR TITLE
Epic/64 comment question voting #170

### PR DESCRIPTION
**Pull request by josgarber6**
Fixed Test Complete Voting error and updated django.yml ready tag #170

### CODE REVIEW

**Review by sebasruii — CHANGES_REQUESTED** [review]
I have encountered an error when accessing the booth once the voting has started, as it is showed on the next screenshot:
image

The steps I have followed to start the voting are:
1. Create a Text question
2. Create a Voting associated with the prior question
3. Start the voting
4. Add a new user
5. Add the new user to the census
6. Navigate to the booth for the voting

Looking at the Google Chrome console, it points to a bug in booth.html, which is caused by the lack of a comma, as it can be seen in the next screenshot:
image

**Comment by josgarber6** [comment]
Complete implementation of Comment question voting.
This PR resolves the following incidents: #64 #92 #66 #68 #108 #134 and #135

**Review by sebasruii — APPROVED** [review]
Great job, now the voting works as expected, I have created a text question voting, voted with two users, stopped, tallied and visualized the results without any difficulties.
image

**Review by alblopnov — APPROVED** [review]
Everything seemed to work perfectly. I was able to create a text question, then the voting, vote with 2 users, stop and tally it. 
Captura de pantalla de 2023-12-02 10-12-10
Captura de pantalla de 2023-12-02 10-13-18

**Pull request merged**
