### PR TITLE
Conf/add vagrant

### PR DESCRIPTION
**Pull request by jmardev**

### CODE REVIEW

**Comment by alvgonfri** [comment]
I think you forgot this:
image

**Review by sebasruii — CHANGES_REQUESTED** [review]
@alvgonfri is right, so I changed the url to ours and tried `vagrant up`, but got this error when it started downloading dependencies:
image

**Comment by sebasruii** [comment]
> but got this error when it started downloading dependencies:
Seems like there's an issue with the available versions of Django in the box

**Review by sebasruii — APPROVED** [review]
Now it works correctly, great job!

**Pull request merged**
