### PR TITLE
Doc/team diary

### PR DESCRIPTION
**Pull request by Thealean28**
This pull request resolves the incident: #90 
This document has been written by @Thealean28 and @alejandromd

### CODE REVIEW

**Review by alvarobernal2412 — APPROVED** [review]
There are some typo in the doc, but the content meet the requirements.

**Comment by mangarrui** [comment]
The document looks perfect, just emphasize that I also made the base home page and I participated in the creation of the base voting.

**Comment by alvgonfri** [comment]
I have also defined the branching strategy in the document "Gestión del repositorio".

**Review by alvgonfri — APPROVED** [review]
Everything looks correct!

**Comment by alvarobernal2412** [comment]
PR protection will be bypassed for merging develop, as it is not possible to execute CI due to the document restriction.

**Pull request merged**
