### PR TITLE
Epic/12 preference voting

### PR DESCRIPTION
**Pull request by josgarber6**

### CODE REVIEW

**Review by alvgonfri — APPROVED** [review]
Lo veo bien.

**Comment by alvarobernal2412** [comment]
This epic needs to be fully implemented

**Review by alvarobernal2412 — CHANGES_REQUESTED** [review]
This PR will be merged when the vote can be carried out correctly and includes testing

**Comment by alvarobernal2412** [comment]
This RP will be closed because this branch needs further development to be completed.

**Pull request closed without merging**
