### PR TITLE
Config update

### PR DESCRIPTION
**Pull request by josgarber6**

### CODE REVIEW

**Comment by alvgonfri** [comment]
El contenido de los commits lo veo bien, pero creo que el nombre de la rama debería ser `feature/config-update`.

**Review by jmartinacu — COMMENTED** [review]
[.gitmessage.txt](https://github.com/EGC-23-24/decide-part-lorca/files/13369689/default.gitmessage.txt)

The .gitmessage file would be better with the changes that the attached file has.

**Review by alejandromd — APPROVED** [review]
Everything is ok.

**Review by alvarobernal2412 — APPROVED** [review]
The gitmessage has been correctly updated and the branch will be renamed after the merge.

**Pull request merged**
