### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by alejandromd**
First version of decide, with all functionalities integrated. Good work team

### CODE REVIEW

**Review by alvgonfri — APPROVED** [review]
Everything looks correct!

**Review by Thealean28 — APPROVED** [review]
It's been a pleasure to work with us. I will always carry you in my heart. gg ❤️

**Comment by goncammej** [comment]
The only member of the group that is worthwhile is pepe8 🫡. I'm sick of working with you guys 🫀

**Review by sebasruii — APPROVED** [review]
Great, all changes are working. Good job team! 🥳

**Comment by alvarobernal2412** [comment]
I really appreciate how hard the work has been done and I am glad to see this decide as a whole group of twelve goofy developers. **Now for the best part, the defence of M3 and the OCCO guys!!!!!** 👑

**Comment by alblopnov** [comment]
If it wasn't for the memes the divorce would have happened. It's been a pleasure🫡 but merge this pr already pls

**Review by josgarber6 — APPROVED** [review]
Due to problems with the codacy reporter this PR is going to be merged taking into account the correct functioning of the tests in develop.

**Pull request merged**
