### PR TITLE
doc: Add create tag handbook #188

### PR DESCRIPTION
**Pull request by Thealean28**

### CODE REVIEW

**Review by goncammej — APPROVED** [review]
Everything looks good. Great job!

**Review by alvarobernal2412 — CHANGES_REQUESTED** [review]
This doc should be refactored for inclusion in the repository management doc.

**Review by alvarobernal2412 — APPROVED** [review]
This section is correctly included in the doc

**Review by josgarber6 — APPROVED** [review]
This change is perfect

**Pull request merged**
