### PR TITLE
Epic/6 census management

### PR DESCRIPTION
**Pull request by davdelpal1**
To test my functionality, you need to enter the following url to see the census management view:

http://127.0.0.1:8000/census/census/

### CODE REVIEW

**Comment by alejandromd** [comment]
The application must be in English, in the section on:
```
http://127.0.0.1:8000/census/details/?id=[id]
``` 
There is content in Spanish, I show you the error:
Captura desde 2023-12-05 20-32-17

**Review by alejandromd — APPROVED** [review]
After correction, the implementation is correct

**Review by alvgonfri — COMMENTED** [review]
I can create a Census with a non-existing Voting and a non-existing User, should I be able to do that?

**Comment by davdelpal1** [comment]
The code has been updated so that it is not possible to create new census with a non-existent voting or voter id.

**Review by alvgonfri — APPROVED** [review]
With the new check before creating a Census, the branch can be merged.

**Comment by alvgonfri** [comment]
Tests launched by Actions did not work, so it looks like you have to fix that to pass the required statuses.

**Comment by davdelpal1** [comment]
I have corrected the census tests

**Comment by davdelpal1** [comment]
The census tests have been corrected, but the store and visualizer tests are still giving errors.

**Comment by davdelpal1** [comment]
The store and visualizer tests have been corrected. #241 #244 #247

**Comment by davdelpal1** [comment]
The store tests have been fixed and all of them are working correctly. #241 #244 #247

**Pull request merged**
