### PR TITLE
Epic/60 voting configurator

### PR DESCRIPTION
**Pull request by alvgonfri**
**First of all, you must add the configurator module to your `local_settings.py` as follows:**
image

Now, you can try the voting configurator by creting any type of voting.

It's available at: http://127.0.0.1:8000/configurator/

Solves #60

### CODE REVIEW

**Comment by mangarrui** [comment]
Looks really good! But there are some small bugs that need to be resolved, one of them is that the configurator needs to be connected to the create_votings button and when you log out and try to access the url configurator/x it should be banned

**Review by alblopnov — CHANGES_REQUESTED** [review]
Tried creating a preference voting and for some reason when I try to vote as a user It does not show the vote button and instead it shows the result button. As you can see the end date is in 2025
Captura de pantalla de 2023-12-17 14-22-24

Captura de pantalla de 2023-12-17 14-47-28

**Comment by alvgonfri** [comment]
> Looks really good! But there are some small bugs that need to be resolved, one of them is that the configurator needs to be connected to the create_votings button and when you log out and try to access the url configurator/x it should be banned

This has been fixed, you can review again

**Comment by mangarrui** [comment]
I think it is because the vote has been closed due to having an associated end_date, making it impossible to vote.

**Comment by alvgonfri** [comment]
> Tried creating a preference voting and for some reason when I try to vote as a user It does not show the vote button and instead it shows the result button. As you can see the end date is in 2025 Captura de pantalla de 2023-12-17 14-22-24
> 
> Captura de pantalla de 2023-12-17 14-47-28

This is happening because when you set a predefined end_date, the voting is finished. This is a problem that must be solved in another fix branch, but it has nothing to do with the configurator. I will report that issue soon.

**Review by mangarrui — APPROVED** [review]
After reviewing the changes, the configurator works. The detailed problem belongs to another module.

**Review by alblopnov — APPROVED** [review]
Okey, everything except the problem I just mentioned works fine and since that problem comes from the booth, your feat seems to work fine👍🏻

**Pull request merged**
