### PR TITLE
Epic/12 preference voting

### PR DESCRIPTION
**Pull request by sebasruii**
Complete implementation of Preference voting.
This PR resolves the following incidences:
#50 #52 #77 #132 #158 and #160

### CODE REVIEW

**Comment by alvarobernal2412** [comment]
I suggest resolving the conflicts and then reopening the issue to restart CI.

**Comment by alvarobernal2412** [comment]
A new feature has been added to the CI, enabling restart via the **_ready_** label. Beforehand, you'll need to copy the commit from 'develop' containing the latest updates.

**Review by Thealean28 — APPROVED** [review]
I created a ranked voting and all works correctly.

**Review by goncammej — CHANGES_REQUESTED** [review]
There are failures in the tests. The failures must be reviewed before approving.

**Review by alvarobernal2412 — APPROVED** [review]
This changes meet the requirements

**Comment by josgarber6** [comment]
This PR solve the issue #12

**Comment by josgarber6** [comment]
This PR solve the incident #118

**Pull request merged**
