### PR TITLE
fix: Correct booth tests when performing ci #230

### PR DESCRIPTION
**Pull request by goncammej**
Waits for the elements to be present on the page before interacting with them.

### CODE REVIEW

**Comment by josgarber6** [comment]
There is an error shown in this image

image

**Comment by josgarber6** [comment]
image

image

In the comment question test there is an error while having access to the booth. It says that the request is badly done

**Review by alejandromd — APPROVED** [review]
The execution of the tests is correct
image

**Review by josgarber6 — APPROVED** [review]
It works perfect!

**Comment by goncammej** [comment]
This PR resolves incident #230

**Pull request merged**
