### PR TITLE
Epic/2 yes no voting

### PR DESCRIPTION
**Pull request by josgarber6**
This PR solve the incident #238

### CODE REVIEW

**Review by alvgonfri — APPROVED** [review]
It works as expected.

**Review by alejandromd — APPROVED** [review]
Now the options for the voting type yes/no are automatically created, the implementation works correctly.

**Comment by alvgonfri** [comment]
Before merging, you must fix the test that failed during Actions testing

**Comment by sebasruii** [comment]
Everything runs well
image

**Review by sebasruii — APPROVED** [review]
Everything runs well
image

**Pull request merged**
