### PR TITLE
feat: Add autopep8 workflow #322

### PR DESCRIPTION
**Pull request by goncammej**

### CODE REVIEW

**Review by alvarobernal2412 — APPROVED** [review]
Amazing workflow!! I suggest refactoring in risky mode🔥

**Comment by goncammej** [comment]
> Amazing workflow!! I suggest refactoring in risky mode🔥

This is a serious project, I suggest you adhere to the formal comment rule it deserves.

**Review by alejandromd — APPROVED** [review]
Amazing!!! Pep8 is working properly

**Comment by goncammej** [comment]
This PR resolves incident #322

**Pull request merged**
